#
# Generated by pypi2aur from pypi package py-nvfan
# Date 2025-04-17 09:35:38
#
pkgname=py-nvfan
_origpkgname=py_nvfan
pkgver=0.1.17
pkgdesc='Automatic Fan Control for NVIDIA Graphics Cards Based on Temperature.'
arch=('any')
url='None'
license=('MIT')
source=('https://files.pythonhosted.org/packages/0b/56/f89d1582903ee3a8299ad34081cf6baad42e0a6b9598d82d2baacd021c39/py_nvfan-0.1.17-py3-none-any.whl')
sha256sums=('1416b6d95ac567666c14b22a391b8750f14543bf00c766d6dd60572f84d2614d')
